steps:
  #build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=europe-west1-b
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod
options:
  logging: CLOUD_LOGGING_ONLY
