apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gcp-devops-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: "gcr.io/learning-397907/gcpdevops"
        ports: 
        - containerPorts: 5000
        env:
            - name: PORT
              value: "5000"
